### LIST ALL EVENTS
GET  http://localhost:8000/events
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU

### FIND A EVENT
GET http://localhost:8000/events/01JTY6JFJ9X5EZWBKRR4WTF21D
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU

### CREATE A EVENT
POST http://localhost:8000/events
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU
Content-Type: application/json

{
  "name": "EVENTO TESTE.",
  "startDate": "2025-06-10T09:00:00Z"
}

### DELETE A EVENT
DELETE http://localhost:8000/events/01JTY6JFJ9X5EZWBKRR4WTF21D
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU

### UPDATE A EVENT
PUT http://localhost:8000/events/01JTY6JFJ9X5EZWBKRR4WTF21D
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU
Content-Type: application/json

{
  "name": "ATUALIZADO",
  "goal": 10
}

### FINISH A EVENT
PATCH  http://localhost:8000/events/01JTY6JFJ9X5EZWBKRR4WTF21D/toggle-end
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU


