### LIST ALL EVENTS
GET  http://localhost:8000/events
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlg1N05RSFZSN0tQUVlCN1ZEVEtRNTNFIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MzAxMjU3LCJleHAiOjE3NDkzODc2NTd9.5--eCH783lgSN6niDq502xYaXJb2R80otKL6iAajH8c

### FIND A EVENT
GET http://localhost:8000/events/01JTY6JFJ9X5EZWBKRR4WTF21D
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlg1N05RSFZSN0tQUVlCN1ZEVEtRNTNFIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MzAxMjU3LCJleHAiOjE3NDkzODc2NTd9.5--eCH783lgSN6niDq502xYaXJb2R80otKL6iAajH8c

### CREATE A EVENT
POST http://localhost:8000/events
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlg1N05RSFZSN0tQUVlCN1ZEVEtRNTNFIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MzAxMjU3LCJleHAiOjE3NDkzODc2NTd9.5--eCH783lgSN6niDq502xYaXJb2R80otKL6iAajH8c
Content-Type: application/json

{
  "name": "EVENTO TESTE2.",
  "startDate": "2025-06-10T09:00:00Z"
}

### DELETE A EVENT
DELETE http://localhost:8000/events/01JTY6JFJ9X5EZWBKRR4WTF21D
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlg1N05RSFZSN0tQUVlCN1ZEVEtRNTNFIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MzAxMjU3LCJleHAiOjE3NDkzODc2NTd9.5--eCH783lgSN6niDq502xYaXJb2R80otKL6iAajH8c

### UPDATE A EVENT
PUT http://localhost:8000/events/01JTY6JFJ9X5EZWBKRR4WTF21D
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlg1N05RSFZSN0tQUVlCN1ZEVEtRNTNFIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MzAxMjU3LCJleHAiOjE3NDkzODc2NTd9.5--eCH783lgSN6niDq502xYaXJb2R80otKL6iAajH8c
Content-Type: application/json

{
  "name": "ATUALIZADO",
  "goal": 10
}

### FINISH A EVENT
PATCH  http://localhost:8000/events/01JTY6JFJ9X5EZWBKRR4WTF21D/toggle-end
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlg1N05RSFZSN0tQUVlCN1ZEVEtRNTNFIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MzAxMjU3LCJleHAiOjE3NDkzODc2NTd9.5--eCH783lgSN6niDq502xYaXJb2R80otKL6iAajH8c


