###
GET http://localhost:8000/partners

###
GET http://localhost:8000/auth/me
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU

###
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "parceiro01",
  "email": "parceiro1@email.com",
  "password": "S&nh@1234",
  "phone": "55955554444",
  "plan": "FREE"
}

###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "parceiro1@email.com",
  "password": "S&nh@1234"
}
###

POST http://localhost:8000/auth/refresh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlJKTVNaNVJQRTg0WkI2QVY0UDRETVlWIiwiaWF0IjoxNzQ0MzgyNTI5LCJleHAiOjE3NDQzODM3Mjl9.FUEY01vQeYAwgm_Cxzixon0QIQcBSJ78JDSGWGrMyjc
###

POST http://localhost:8000/auth/logout
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlFSUjhNUVBRODhEWUVaMFpRSkRFWEhDIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQzNTI4Mzg2LCJleHAiOjE3NDM1Mjg0NDZ9.IK5jwMOxBU45Bc-UsClaHHu0kBxftrelCK4UTTpon_c
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlFTQURYV0JNQjg4MlZWTTBDTU45RFpRIiwiaWF0IjoxNzQzNTMzNTM3LCJleHAiOjE3NDQxMzgzMzd9.AU4MZmLJBtHjXkS-I6KISexVyzx-j6NfDMJYX-8pRKY

###
DELETE http://localhost:8000/auth/01JQCV96WH5247M9AMN9R5VZRD

###
PUT http://localhost:8000/partner/01JTRW5C4T550HK6ES3HDX1AXS
Content-Type: application/json

{
  "name": "Anthony",
  "phone":"(54) 99210-1557"
}

###
