POST http://localhost:8000/pending-action
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU
Content-Type: application/json

{
  "eventId": "01JSA47TFAC73229AKNBKRAXZH",
  "sellerId": "01JSJ3DRZQ9P855P5RPM9XF1Q3",
  "actionType": "CREATE_SALE",
  "payload": {
    "eventId": "01JSA47TFAC73229AKNBKRAXZH",
    "productId": "01JSA48M6HPG7V41D7WG8S79B7",
    "sellerId": "01JSJ3DRZQ9P855P5RPM9XF1Q3",
    "quantity": 7
  }
}

###
GET  http://localhost:8000/pending-action
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU
Content-Type: application/json

###
POST  http://localhost:8000/pending-action/approve-reject
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU
Content-Type: application/json

{
  "pendingActionId": "01JSVNYCVG40BQW2VRJ2B8RMDW",
  "approve": true
}

###
POST http://localhost:8000/pending-action
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU
Content-Type: application/json

{
  "targetId": "01JSVNQM9DJR5QW7GRZ5YK9RCP",
  "eventId": "01JSA47TFAC73229AKNBKRAXZH",
  "sellerId": "01JSJ3DRZQ9P855P5RPM9XF1Q3",
  "actionType": "DELETE_SALE",
  "payload": {}
}
###
POST http://localhost:8000/pending-action
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU
Content-Type: application/json

{
  "targetId": "01JSVN8E78B9YWTJDRSE10CNXF",
  "eventId": "01JSA47TFAC73229AKNBKRAXZH",
  "sellerId": "01JSJ3DRZQ9P855P5RPM9XF1Q3",
  "actionType": "UPDATE_SALE",
  "payload": {
    "eventId": "01JSA47TFAC73229AKNBKRAXZH",
    "productId": "01JSA48M6HPG7V41D7WG8S79B7",
    "sellerId": "01JSJ3DRZQ9P855P5RPM9XF1Q3",
    "quantity": 1
  }
}

