###
GET http://localhost:8000/products
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM

###
GET http://localhost:8000/product/01JRJNPAFM575GJP095FCBHQHW
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM

###
POST http://localhost:8000/products
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM
# Authorization: Bearer <seu_token_jwt_aqui>
Content-Type: application/json

{
  "name": "bros",
  "price": 8000.80
}

###
DELETE http://localhost:8000/products/01JRJNPAFM575GJP095FCBHQHW
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM


###
PUT http://localhost:8000/products/01JRJNPAFM575GJP095FCBHQHW
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM
Content-Type: application/json

{
  "name": "START - ATU2",
  "price": 8000.80
}


###
