###
GET http://localhost:8000/events/01JSA47TFAC73229AKNBKRAXZH/sales
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU
Content-Type: application/json

###
GET http://localhost:8000/events/01JSA47TFAC73229AKNBKRAXZH/sales/01JSMPYKPSRQ3B802HBYV0ZYQ0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU
Content-Type: application/json


###
POST http://localhost:8000/events/01JSA47TFAC73229AKNBKRAXZH/sales
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU
# Authorization: Bearer <seu_token_jwt_aqui>
Content-Type: application/json

{
  "sellerId": "01JSA7NWTMZ69QVF7PA5DHJB0P",
  "productId": "01JSA48M6HPG7V41D7WG8S79B7",
  "quantity": 11
}

###
DELETE http://localhost:8000/events/01JSA47TFAC73229AKNBKRAXZH/sales/01JSMPYKPSRQ3B802HBYV0ZYQ0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU


###
PUT http://localhost:8000/events/01JSA47TFAC73229AKNBKRAXZH/sales/01JSMPYKPSRQ3B802HBYV0ZYQ0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlZUWkZRNFhLUkZTNzBCM1dLWkY5Rk5EIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ4MTc5MDc3LCJleHAiOjE3NDgxODI2Nzd9.trdKZ1RErORjuI5J9QB3lbiVtCnC97-nyzoWdsU_aKU
Content-Type: application/json

{
  "quantity": 9
}



###


POST https://api.z-api.io/instances/3E040AAFC4E040626FFFA622FD8B21DA/token/AEFF4AF21E6FBAA4689AD08C/send-text
Content-Type: application/json
client-token: "F5f16fc353fcd4095ba61b639f1e26844S"

{
  "phone": "5554992101557",
  "message": "Welcome to *Z-API*"
}