### LIST ALL SELLER EVENT
GET http://localhost:8000/events/01JVX0SV6CVCYAKSB315A59ZCR/sellers/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM
Content-Type: application/json

### LIST ALL EVENT SELLER
GET http://localhost:8000/sellers/01JVTZG9R3P7YZM1B7KJYKQSKK/events/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM
Content-Type: application/json

### FIND
GET http://localhost:8000/events/01JVX0SV6CVCYAKSB315A59ZCR/sellers/01JVTZG9R3P7YZM1B7KJYKQSKK/sellerEvents/01JSANK1DV9W3W6T2989FN51NT
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM
Content-Type: application/json


### CREATE
POST http://localhost:8000/events/01JVX0SV6CVCYAKSB315A59ZCR/sellers/01JVTZG9R3P7YZM1B7KJYKQSKK
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM
Content-Type: application/json

{
  "quantity": 99,
}

### DELETE
DELETE http://localhost:8000/events/01JVX0SV6CVCYAKSB315A59ZCR/sellers/01JVTZG9R3P7YZM1B7KJYKQSKK/sellerEvents/01JSAGXRKJQVNXMPYR3TVH3N56
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM


### PUT
PUT http://localhost:8000/events/01JVX0SV6CVCYAKSB315A59ZCR/sellers/01JVTZG9R3P7YZM1B7KJYKQSKK/sellerEvents/01JSAGXRKJQVNXMPYR3TVH3N56
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM
Content-Type: application/json

{
  "quantity": 99,
}

### Invite
POST  http://localhost:8000/events/01JVX0SV6CVCYAKSB315A59ZCR/guest/01JVX0TK9JWEC60TYVNKJZG7X4
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM
Content-Type: application/json


### Invite
GET  http://localhost:8000/events/01JVX0SV6CVCYAKSB315A59ZCR/guest/01JVX0TK9JWEC60TYVNKJZG7X4
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM
Content-Type: application/json