### LIST ALL SELLER EVENT
GET http://localhost:8000/events/01JTRXJDGPZN6Y1FQY32NPJT58/sellers/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlRSVzVDNFQ1NTBISzZFUzNIRFgxQVhTIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ3MDcwNTI0LCJleHAiOjE3NDc2NzUzMjR9.ojZjzVrwFWqVDnNvwCmR-HqKWlM4S0jcaJv-nZQmXv0
Content-Type: application/json

### LIST ALL EVENT SELLER
GET http://localhost:8000/sellers/01JSA7NWTMZ69QVF7PA5DHJB0P/events/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlRSVzVDNFQ1NTBISzZFUzNIRFgxQVhTIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ3MDcwNTI0LCJleHAiOjE3NDc2NzUzMjR9.ojZjzVrwFWqVDnNvwCmR-HqKWlM4S0jcaJv-nZQmXv0
Content-Type: application/json

### FIND
GET http://localhost:8000/events/01JTRXJDGPZN6Y1FQY32NPJT58/sellers/01JSA7NWTMZ69QVF7PA5DHJB0P/sellerEvents/01JSANK1DV9W3W6T2989FN51NT
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlRSVzVDNFQ1NTBISzZFUzNIRFgxQVhTIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ3MDcwNTI0LCJleHAiOjE3NDc2NzUzMjR9.ojZjzVrwFWqVDnNvwCmR-HqKWlM4S0jcaJv-nZQmXv0
Content-Type: application/json


### CREATE
POST http://localhost:8000/events/01JTRXJDGPZN6Y1FQY32NPJT58/sellers/01JSA7NWTMZ69QVF7PA5DHJB0P
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlRSVzVDNFQ1NTBISzZFUzNIRFgxQVhTIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ3MDcwNTI0LCJleHAiOjE3NDc2NzUzMjR9.ojZjzVrwFWqVDnNvwCmR-HqKWlM4S0jcaJv-nZQmXv0
Content-Type: application/json

{
  "quantity": 99,
}

### DELETE
DELETE http://localhost:8000/events/01JTRXJDGPZN6Y1FQY32NPJT58/sellers/01JSA7NWTMZ69QVF7PA5DHJB0P/sellerEvents/01JSAGXRKJQVNXMPYR3TVH3N56
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlRSVzVDNFQ1NTBISzZFUzNIRFgxQVhTIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ3MDcwNTI0LCJleHAiOjE3NDc2NzUzMjR9.ojZjzVrwFWqVDnNvwCmR-HqKWlM4S0jcaJv-nZQmXv0


### PUT
PUT http://localhost:8000/events/01JTRXJDGPZN6Y1FQY32NPJT58/sellers/01JSA7NWTMZ69QVF7PA5DHJB0P/sellerEvents/01JSAGXRKJQVNXMPYR3TVH3N56
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlRSVzVDNFQ1NTBISzZFUzNIRFgxQVhTIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ3MDcwNTI0LCJleHAiOjE3NDc2NzUzMjR9.ojZjzVrwFWqVDnNvwCmR-HqKWlM4S0jcaJv-nZQmXv0
Content-Type: application/json

{
  "quantity": 99,
}

### Invite
POST  http://localhost:8000/events/01JTRXJDGPZN6Y1FQY32NPJT58/guest/01JTRYD12F2HBWYMH1K4JQDPDM
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlRSVzVDNFQ1NTBISzZFUzNIRFgxQVhTIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ3MDcwNTI0LCJleHAiOjE3NDc2NzUzMjR9.ojZjzVrwFWqVDnNvwCmR-HqKWlM4S0jcaJv-nZQmXv0
Content-Type: application/json


### Invite
GET  http://localhost:5173/guest/01JTRYD12F2HBWYMH1K4JQDPDM?partnerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlRSVzVDNFQ1NTBISzZFUzNIRFgxQVhTIiwiaWF0IjoxNzQ3MTU5MTQxLCJleHAiOjE3NDc3NjM5NDF9.LzS_kfns-vr7nvETI20OvlUX_isFQnoSiu4QsPjFPeM&guestToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlRSWUQxMkYySEJXWU1IMUs0SlFEUERNIiwiZW1haWwiOiJhbnRob255QGdtYWlsLmNvbSIsImlhdCI6MTc0NzE1OTE0MSwiZXhwIjoxNzQ3MjQ1NTQxfQ.wkyMZBFPP27rBZku5EqjNfjk4wdiSUv52gmezAAcTcE
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlRSVzVDNFQ1NTBISzZFUzNIRFgxQVhTIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ3MDcwNTI0LCJleHAiOjE3NDc2NzUzMjR9.ojZjzVrwFWqVDnNvwCmR-HqKWlM4S0jcaJv-nZQmXv0
Content-Type: application/json
