###
GET http://localhost:8000/sellers
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM

###
GET http://localhost:8000/sellers/01JVX0TK9JWEC60TYVNKJZG7X4
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM

###
GET http://localhost:8000/sellers/email/awl-7@live.com
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM

###
POST http://localhost:8000/sellers
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM
# Authorization: Bearer <seu_token_jwt_aqui>
Content-Type: application/json

{
  "name": "OTHER XxX.",
  "email": "vendedor@04.com",
  "phone": "55992101557"
}

###
DELETE http://localhost:8000/sellers/01JTRYD12F2HBWYMH1K4JQDPDM
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM


###
PUT http://localhost:8000/sellers/01JVX0TK9JWEC60TYVNKJZG7X4
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlgwSlowVjlGNlFCNTVHTVlHQUpBMVBNIiwiZW1haWwiOiJwYXJjZWlybzFAZW1haWwuY29tIiwiaWF0IjoxNzQ5MTU0MTg3LCJleHAiOjE3NDkyNDA1ODd9.MOKMnPIdXBogaJOtCw9B0a90PFSbOSKyU5pXOwZHzVM
Content-Type: application/json

{
  "name": "Vendedor 50 - ATUALIZADO.",
  "email": "vendedor@00.com",
  "phone": "54992101557"
}



###
